---

domain: staging.openfoodfrance.org
host_id: fr-staging
rails_env: staging

admin_email: admin@openfoodfrance.org

mail_domain: openfoodfrance.org

unicorn_timeout: 120

users_sysadmin:
  - "{{ core_devs }}"
  - paco
  - hugo
  - filipe
