---

- name: extract host_id from filepath
  set_fact:
    secrets_host_id: "{{ secrets_host_path.path.split('/tmp/ofn-secrets/')[1] }}"

- name: copy {{ secrets_host_id }} secrets file to relevant host_vars directory
  copy:
    src: "{{ secrets_host_path.path }}/secrets.yml"
    dest: "../inventory/host_vars/{{ groups[secrets_host_id][0] }}/secrets.yml"
    decrypt: no
