---

domain: www.openfoodfrance.org
host_id: fr-prod
rails_env: production

admin_email: admin@openfoodfrance.org

mail_domain: openfoodfrance.org

unicorn_timeout: 240
unicorn_workers: 4

certbot_domains:
  - www.openfoodfrance.org
  - openfoodfrance.org

postgres_listen_addresses:
  - '*'

custom_hba_entries:
  - { type: hostssl, database: "{{ db }}", user: zapier, address: '54.86.9.50/32', auth_method: md5 }

enable_nginx_logging: true
enable_rails_apm: "true" # has to be explicitly defined as a string due to some datadog bug
