--- # Rollback

- name: fetch stats of rollback symlink
  stat:
    path: "{{ rollback_path }}"
  register: rollback_symlink

- name: symlink rollback source to current path
  file:
    src: "{{ rollback_symlink.stat.lnk_source }}"
    dest: "{{ current_path }}"
    owner: "{{ unicorn_user }}"
    state: link
    force: yes
  become: yes
  become_user: "{{ unicorn_user }}"
  notify: reload unicorn

- name: restore database
  include_role:
    name: db_restore
    tasks_from: restore_database
  vars:
    database_dump_path: "{{ rollback_sql_path }}"
