---

- name: stop unicorn and delayed_job
  service:
    name: "{{ service_name }}"
    state: stopped
  loop:
    - "unicorn_{{ app }}"
    - "delayed_job_{{ app }}"
  loop_control:
    loop_var: service_name
  become: yes
  become_user: root

- name: close active db connections # noqa 301
  shell: |
    psql -c "REVOKE CONNECT ON DATABASE {{ db }} FROM public;
    SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='{{ db }}' AND pid <> pg_backend_pid();"
  become: true
  become_user: postgres

- name: drop database
  postgresql_db:
    name: "{{ db }}"
    state: absent
  become: true
  become_user: postgres

- name: recreate database
  postgresql_db:
    name: "{{ db }}"
    owner: "{{ db_user }}"
    encoding: "UTF-8"
    lc_ctype: "{{ postgres_encoding }}"
    lc_collate: "{{ postgres_encoding }}"
    state: present
  become: true
  become_user: postgres

- name: restore database from backup
  postgresql_db:
    name: "{{ db }}"
    owner: "{{ db_user }}"
    state: restore
    target: "{{ database_dump_path }}"
  become: true
  become_user: postgres

- name: restart unicorn and delayed_job
  service:
    name: "{{ service_name }}"
    state: started
  loop:
    - "unicorn_{{ app }}"
    - "delayed_job_{{ app }}"
  loop_control:
    loop_var: service_name
  become: yes
  become_user: root
