---

domain: www.openfoodnetwork.be
host_id: be-prod
rails_env: production

admin_email: admin@openfoodnetwork.be

mail_domain: openfoodnetwork.be

certbot_domains:
  - www.openfoodnetwork.be
  - openfoodnetwork.be
