--- # common

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 86400 # seconds = 60*60*24 seconds = 24 hours
  become: yes
  tags: packages

- name: install base packages
  apt:
    name: "{{ packages }}"
  become: yes
  vars:
    packages:
      # Ansible support
      - python-pycurl
      - python-psycopg2
      - python3-psycopg2

      # unknown why or if needed
      # The playbooks run without these dependencies,
      # but they may be hidden run time dependencies
      # like imagemagick.
      - acl
      - nodejs
      - curl

      # build ruby and gems
      - build-essential

      # manage code
      - git-core

      # OFN dependencies
      - imagemagick
      - libpq-dev
      - zlib1g-dev
      - libssl-dev
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - memcached
      - libxrender1
  tags: packages

- name: add memcached configuration
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    mode: 0644
  become: yes
  notify:
    - restart memcached
