---

# This playbook sets up proxying for `letsencrypt` validation checks from one server to another.
# This is used in the tricky process of creating a valid multi-domain certificate on a *new* server
# (before a migration), without affecting anything on the current production server.

# Requires extra_var: `proxy_target`, which should be a domain or IP address, eg:
# ansible_playbook playbooks/letsencrypt_proxy --limit current-prod -e "proxy_target=new-prod.org"

- name: letsencrpyt acme challenge proxing
  hosts: ofn_servers
  remote_user: "{{ user }}"

  vars:
    nginx_acme_challenge_config: |+
      location '/.well-known/acme-challenge' {
        # Temporary proxy of letencrypt certificate validation checks
        proxy_pass http://{{ proxy_target }}/.well-known/acme-challenge;
        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-for $remote_addr;
        port_in_redirect off;
        proxy_connect_timeout 300;
      }

  roles:
    - role: jdauphant.nginx
      become: yes
