---
- name: PostgreSQL production tuning
  hosts: ofn_servers
  remote_user: "{{ user }}"

  tasks:
    - name: Gather postgres installation details
      include_role:
        name: geerlingguy.postgresql
        tasks_from: variables

    - name: Add tuning configuration
      copy:
        content: |
          shared_buffers = {{ ( ansible_memtotal_mb / 4 ) | int }}MB
          effective_cache_size = {{ ( ( ansible_memtotal_mb / 4 ) * 3 ) | int }}MB
          maintenance_work_mem = {{ ( ansible_memtotal_mb / 16 ) | int }}MB
          wal_buffers = 16MB
          work_mem = 64MB
        dest: "{{ postgresql_config_path }}/conf.d/tuning.conf"
      become: yes
      become_user: postgres
      notify: restart postgres
      when: remove_postgres_tuning is undefined

    - name: Optionally remove tuning configuration
      file:
        path: "{{ postgresql_config_path }}/conf.d/tuning.conf"
        state: absent
      when: remove_postgres_tuning is defined

  handlers:
    - name: restart postgres
      service:
        name: postgresql
        state: restarted
      become: yes
